// ai-team service worker — generated by buildServiceWorkerScript (V122)
const CACHE_NAME = "ai-team-runtime-v1";
const STATIC_CACHE = "ai-team-static-v1";
const API_CACHE = "ai-team-api-v1";
const OFFLINE_URL = "/offline.html";
const PRECACHE_URLS = ["/","/index.html","/offline.html"];
const CACHE_FIRST_PATHS = ["/assets/","/icons/","/data/"];
const NETWORK_FIRST_PATHS = ["/api/"];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.filter((k) => ![STATIC_CACHE, API_CACHE, CACHE_NAME].includes(k))
            .map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET') return;
  if (url.origin !== self.location.origin) return;

  // Cache-first for static assets
  if (CACHE_FIRST_PATHS.some((p) => url.pathname.startsWith(p))) {
    event.respondWith(
      caches.match(event.request).then((cached) => cached || fetch(event.request))
    );
    return;
  }

  // Network-first for API
  if (NETWORK_FIRST_PATHS.some((p) => url.pathname.startsWith(p))) {
    event.respondWith(
      fetch(event.request)
        .then((res) => {
          const clone = res.clone();
          caches.open(API_CACHE).then((cache) => cache.put(event.request, clone));
          return res;
        })
        .catch(() => caches.match(event.request).then((cached) => cached || caches.match(OFFLINE_URL)))
    );
    return;
  }

  // Default: network with cache fallback
  event.respondWith(
    fetch(event.request).catch(() => caches.match(event.request).then((cached) => cached || caches.match(OFFLINE_URL)))
  );
});
